### ISSUE TITLE
Not getting this to work...

### ISSUE THREAD

**Issue by phoob** [ostark/craft-async-queue#1]
Tried installing this in a setup with Craft 3beta 30 on ubuntu 16.04 with php-fpm (php7.0.x). Installed it, tried triggering a queue job (by saving an article), but the jobs are stuck on "waiting" in the CP. They don't seem to be executed. My php binary is in /usr/bin. I'll gladly contribute more info on this issue, but I'm not really sure what you'd need.. Using ./craft queue/listen works – as do the AJAX/default handling.

Regards, Peter

**Comment by ostark** [comment]
thx, @phoob 
haven't tested with `Craft 3beta 30`, but I can't imagine that release had any breaking changes. I'll give it a try and let you know.

**Comment by ostark** [comment]
@phoob, can you try the latest release 1.1.2 and share your logs?
```
grep 'craft-async-queue' storage/logs/web.log
```
