### ISSUE TITLE
decrement in ProcessPool doesn't seem to be called

### ISSUE THREAD

**Issue by nfourtythree** [ostark/craft-async-queue#11]
It seems that tasks are only ever run once by async queue. The cache of `async-queue-pool` seems to hit the max and never get less, making me assume that the `decrement()` function isn't being called.

This means when `$this->getPool()->canIUse()` is called, `false` is always return after the first tasks have been put in.

I have a module that generates a decent number of tasks so getting this working would be a massive help!

Thanks!

**Comment by ostark** [comment]
Hey @nfourtythree 

thanks for your report! I tried to reproduce it by adding debug log after `cache->get()`
Here is the output:

```
$ grep crement *.log

web.log:2018-06-27 19:28:43 [127.0.0.1][1][-][trace][async_queue] increment() -> current poolUsage: 0
web.log:2018-06-27 19:28:43 [127.0.0.1][1][-][trace][async_queue] increment() -> current poolUsage: 1
web.log:2018-06-27 19:28:49 [127.0.0.1][1][-][trace][async_queue] increment() -> current poolUsage: 0
web.log:2018-06-27 19:28:49 [127.0.0.1][1][-][trace][async_queue] increment() -> current poolUsage: 1

console.log:2018-06-27 19:28:43 [-][-][-][trace][async_queue] decrement() -> current poolUsage: 2
console.log:2018-06-27 19:28:44 [-][-][-][trace][async_queue] decrement() -> current poolUsage: 1
console.log:2018-06-27 19:28:50 [-][-][-][trace][async_queue] decrement() -> current poolUsage: 2
console.log:2018-06-27 19:28:50 [-][-][-][trace][async_queue] decrement() -> current poolUsage: 1

```

that's the expected behaviour.

---

Maybe your issue is not related to the pool. I'm happy to help, I'm on craft slack as well.

**Comment by nfourtythree** [comment]
Hey @ostark thanks for the message on here and on Slack.

I have managed to sort it, it was a combination of cache, some code that needed fixing but mostly the fact I had been in the office for far too many hours in the day.

I will note down for others that might stumble across this issue, I had issues locally and on the staging server. One thing that helped get things flowing, if you are having issues, was to completely nuke the `storage/runtime` folder.

**Comment by blasvicco** [comment]
Hi, I have the same issue. Seems that for some reason the hook `Command::EVENT_AFTER_ACTION` is never being call.
I'm trying to find out why is that.

**Comment by blasvicco** [comment]
I found that in the `Plugin.php file` the hook
```PHP
// where Command is craft\queue\Command
Event::on(
            Command::class,
            Command::EVENT_AFTER_ACTION,
            function (ActionEvent $event) {
                if ('run' === $event->action->id) {
                    $this->getPool()->decrement();
                }
            }
);
```
is never being called.

But If I use yii\base\Controller instead:
```PHP
Event::on(
            Controller::class,
            Controller::EVENT_AFTER_ACTION,
            function (ActionEvent $event) {
                if ('run' === $event->action->id) {
                    $this->getPool()->decrement();
                }
            }
);
```
Then It works but not quite well, because it is being executed only when the whole queue is processed and not for each item in the queue.

Please refer to https://github.com/ostark/craft-async-queue/pull/13 for more detail.

```
In use
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 1
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 2
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 3
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
CONTROLLER::EVENT_AFTER_ACTION TRIGGERED!!!
In use
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 1
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 2
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 3
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
CONTROLLER::EVENT_AFTER_ACTION TRIGGERED!!!
In use
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 1
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 2
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 3
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 4
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 5
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 6
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
In use 7
nice /usr/bin/php craft queue/run -v > /dev/null 2>&1 &
CONTROLLER::EVENT_AFTER_ACTION TRIGGERED!!!
```

**Comment by ostark** [comment]
@blasvicco Thanks, I'll investigate

**Comment by ostark** [comment]
I guess it's related to https://github.com/craftcms/cms/issues/3332
At the moment `'run' === $event->action->id` this is never the case , no matter the event (Controller::EVENT_AFTER_ACTION vs Command::EVENT_AFTER_ACTION).

These events are only fired for the `exec` action->id ...

**Comment by blasvicco** [comment]
@ostark what I found is that the event hook `COMMAND::EVENT_AFTER_ACTION` is only being triggered if I execute the command `./craft queue/run` manually in the console (shell), but it is not if, for example, I modify an entry in the web app.

What I found also, is that maybe instead of that hook we can use `Queue::EVENT_AFTER_EXEC`.
This one is being triggered after each task that was executed from the queue giving us the event id.
```PHP
Event::on(
            Queue::class,
            Queue::EVENT_AFTER_EXEC,
            function (ExecEvent $event) {
                file_put_contents('/var/www/app/storage/logs/async-queue.log', "QUEUE::EVENT_AFTER_EXEC TRIGGERED event->id " . $event->id . "\n", FILE_APPEND);
                if ('run' === $event->id) {
                    file_put_contents('/var/www/app/storage/logs/async-queue.log', "COMMAND::EVENT_AFTER_EXEC TRIGGERED!!!\n", FILE_APPEND);
                    $this->getPool()->decrement();
                }
            }
        );
```
For example:
```
QUEUE::EVENT_AFTER_EXEC TRIGGERED event->id 2977
QUEUE::EVENT_AFTER_EXEC TRIGGERED event->id 2979
QUEUE::EVENT_AFTER_EXEC TRIGGERED event->id 2981
QUEUE::EVENT_AFTER_EXEC TRIGGERED event->id 2983
```

That means, that if we want to use this hook we need to modify the way the pool is caching the usage.
We should increment the pool caching the event->id and only decrement it if the id match with one in the pool.

**Comment by blasvicco** [comment]
@ostark Nope, we are using database.

**Comment by ostark** [comment]
Windows?

**Comment by blasvicco** [comment]
Distro: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-037)
(gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)

PHP: 7.0.31-1+ubuntu14.04.1+deb.sury.org+1 (cli) Zend Engine v3.0.0
Craft CMS: 3.0.32
craft-async-queue: 1.3.3

**Comment by ostark** [comment]
Let's switch to a private channel - Slack?

**Comment by nfourtythree** [comment]
@ostark @blasvicco I am following along with this so would be good to know if there was anything that came out of the private discussion 👍

**Comment by ostark** [comment]
@nfourtythree I'll review the logs this evening.

**Comment by ostark** [comment]
@blasvicco @blasvicco Feel free to extend the tests suite to reproduce the error :-)
https://github.com/ostark/craft-async-queue/tree/v2/tests

PS: Don't use v2 in production so far!
