### ISSUE TITLE
Daemon is never started..?

### ISSUE THREAD

**Issue by roberttolton** [ostark/craft-async-queue#12]
Hi, thanks for the great work in this plugin.

However, after installing it in an Ubuntu system (Forge provisioned) with the latest Craft 3 release, there's just no daemon running..?

Is there other setup needed? Do I need to disable automatic task running myself?

Here's an output of `ps auxf | grep php`:

```
forge     5504  0.0  0.0  14856   944 pts/0    S+   12:21   0:00  |           \_ grep --color=auto php
root      3832  0.0  0.2 1383384 40552 ?       Ss   11:08   0:00 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
forge     5375  4.7  0.5 1484660 90000 ?       S    12:08   0:35  \_ php-fpm: pool www
forge     5376  4.7  0.5 1478548 84740 ?       S    12:08   0:35  \_ php-fpm: pool www
forge     5446  4.9  0.5 1479788 85464 ?       S    12:09   0:35  \_ php-fpm: pool www
```

The above was captured during a 'deleting stale template caches' task, so there was at least several tasks in the queue - it seems like `php-fpm` is still doing the work.

`web.log` contains no instances of `craft-async-queue`, `phperrors.log` lists nothing.

Any ideas?

**Comment by roberttolton** [comment]
On closer inspection, with running the command myself, I get:

```
Unsupported DB driver value in /vendor/craftcms/cms/src/config/DbConfig.php:190
```

My database credentials are set as environment variables from NGINX, not as `.env` or within a config file. I'm guessing the command has no idea..?

**Comment by roberttolton** [comment]
Believe to have been solved. So the command wasn't picking up on environment variables I had set, because they were set through NGINX only - nothing the cli could get!

Adding the `.env.php` file to my live setup (using @andrew.welch's multi-env setup) solved the issue. The command could get the right variables to do it's job.

**Comment by ostark** [comment]
Direct (real) env vars should work as expected
