### ISSUE TITLE
Add environment config to disable the plugin

### ISSUE THREAD

**Issue by smcyr** [ostark/craft-async-queue#14]
It would be nice to have an environment config (example: DISABLE_ASYNC_QUEUE) for cases where you have continuous integration (with Jenkins for example) and multiple servers (staging, preprod, prod), but some of the servers don't have proc_open enabled. With Schematic and now Craft 3.1 project config, the plugin will be installed automatically on all servers even if proc_open is not there.
Thanks!

**Comment by ostark** [comment]
Will be available in V2 https://github.com/ostark/craft-async-queue/tree/v2

https://github.com/ostark/craft-async-queue/commit/f55340ef5c084fd42b8a00538ed509df3960db0a
