### ISSUE TITLE
PHP >= 7.1.3  required for 1.4.0

### ISSUE THREAD

**Issue by almeric** [ostark/craft-async-queue#15]
Hi,
First of all thank you for this great plugin!

One small problem though, the composer/process package upgrade to 4.0 also bumped the minimum PHP version to 7.1.3. Was this intentional?

Ubuntu 16.04 has php 7.0.32 (which is the OS we're running on out servers) so this breaks our deployments.

**Comment by ostark** [comment]
Hi Almeric,

Thanks for using the plugin :-)

Yes, intentional, since 7.0 became EOL two weeks ago. I updated the requirements with a hint:
https://github.com/ostark/craft-async-queue#requirements

Oli

**Comment by almeric** [comment]
Righto, we'll just pin the version then.

Thanks!

**Comment by jsunsawyer** [comment]
Just went to test this out and the requirement made it too difficult to install.

I use brew's php and their current stable version is behind your requirement. https://formulae.brew.sh/formula/php@7.1

Also, our ServerPilot/Digital Ocean setup is running on php 7.1.26

Am I missing something or does this requirement seem too strict?

**Comment by ostark** [comment]
7.1.25 is 22 patch releases after 7.1.3, you fullfil the requirement

**Comment by ostark** [comment]
@jsunsawyer

Have you tried all this? https://github.com/ostark/craft-async-queue/blob/master/README.md#installation

**Comment by jsunsawyer** [comment]
Hmmm. It looks like I needed to change my `composer.json` file's `config.platform.php` version. It was set to `7.0`. I updated to `7.1.26` to match our staging environment. I wasn't aware of this setting and this is the first time it has caused me issues.

_Those version numbers always confuse me haha. I always look at them like numbers with decimals. Whoops!_
