### ISSUE TITLE
Install failed: Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by kaspar-allenbach** [ostark/craft-async-queue#17]
I want to install AsyncQueue on a fresh install under php `27.2.10`

I get this error:

> composer require ostark/craft-async-queue
> Using version ^2.0 for ostark/craft-async-queue
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.

>   Problem 1
>     - Installation request for ostark/craft-async-queue ^2.0 -> satisfiable by ostark/craft-async-queue[2.0.0].
>     - Conclusion: remove symfony/process v3.3.6
>     - ostark/craft-async-queue 2.0.0 requires symfony/process ^4.2.0 -> satisfiable by symfony/process[v4.2.0, v4.2.1, v4.2.2, v4.2.3].
>     - Can only install one of: symfony/process[v4.2.0, v3.3.6].
>     - Can only install one of: symfony/process[v4.2.1, v3.3.6].
>     - Can only install one of: symfony/process[v4.2.2, v3.3.6].
>     - Can only install one of: symfony/process[v4.2.3, v3.3.6].
>     - Installation request for symfony/process (installed at v3.3.6) -> satisfiable by symfony/process[v3.3.6].

I tried 

> composer config platform --unset

But I can't install it.

**Comment by ostark** [comment]
@kaspar-allenbach Thanks for your report.
After removing the `config platform` thingy, can you run `composer update` to update all dependencies?

If this does not work, can you tell me the output of

```
composer why symfony/process
```

**Comment by kaspar-allenbach** [comment]
`composer update` did the trick. thank you
