### ISSUE TITLE
Feature Request: Store paths without siteUrl

### ISSUE THREAD

**Issue by luke-nehemedia** [ostark/craft-async-queue#19]
I just moved a site from one domain to another. Sadly, the urls of the images are all stored as full paths. Since the url changed, the plugin had to walk through all images, which took ages and was quite demanding for the server. 

I think it would be a good solution to store the relative path after the siteUrl.

**Comment by ostark** [comment]
How is this related to this plugin?

**Comment by luke-nehemedia** [comment]
I am sorry - wrong plugin! 
You plugin is working great! Thanks a lot!
