### ISSUE TITLE
Jobs from Abandoned Cart for Craft Commerce 2 plugin not running

### ISSUE THREAD

**Issue by RandomJo** [ostark/craft-async-queue#20]
I'm using your plugin in combination with the Abandoned Cart for Craft Commerce 2 plugin, and I'm running into issues with the queue not piggybacking on HTTP requests when the AsyncQueue plugin is enabled. What I see in Utilities > Async Queue Test is that one job is waiting. I also see it as pending in the CP's left nav. It just hangs around as pending though and never completes even when clicking around in the admin to generate requests. As soon as I disabled AsyncQueue and create a new HTTP request, the jobs run. Because it works as expected when AsyncQueue is disabled, that leads me to think either something is wrong with AsyncQueue or I'm misunderstanding how it's supposed to work.

As I understand it, this plugin is not supposed to change how the jobs in the queue are triggered, it's only supposed to delegate them to a background process, right?

Craft CMS Version: 3.1.12
AsyncQueue Version: 2.0.0
Abandoned Cart for Craft Commerce 2 Version: 1.0.1
Host: fortrabbit

**Comment by ostark** [comment]
Thanks for your report, @RandomJo
I'll try to reproduce / understand your issue.

**Comment by ostark** [comment]
I assume you run `php craft abandoned-cart/reminders/schedule-emails` via cron but you don't run ` php craft queue/run`. The "issue" is related to the delay (1 and 12 hours by default) Abandoned Cart is making use of.

I can think of a workaround.

**Comment by RandomJo** [comment]
That's correct. We're on the universal stack on fortrabbit, and they limit us to one cron command (and we can't hack it by using && to tie commands together). So I figured we could live with the running the queue based on HTTP requests.

Could you tell me more about how the issue is related to the Abandoned Cart delay? Why does it make a difference when AsyncQueue is running versus when Craft's native queue logic is in place?

I'd love to hear your thoughts on a workaround. Thanks so much for looking into it!

**Comment by yiska** [comment]
> I assume you run `php craft abandoned-cart/reminders/schedule-emails` via cron but you don't run ` php craft queue/run`. The "issue" is related to the delay (1 and 12 hours by default) Abandoned Cart 

@ostark Are you saying we have to run `craft queue/run`  in cron to get tasks to run properly with version 2.0.0? We did not have to use that method in 1.4.0. Our system has multiple web nodes that scale up/down automatically so we cannot have a cron job running on every node. Is there some other recommendation to manage the queue runner now?

**Comment by ostark** [comment]
@yiska Is your issue/question related to `abandoned-cart`?

**Comment by yiska** [comment]
@ostark No it isn't but it is related to tasks not running after upgrading to 2.0.0. I commented on https://github.com/ostark/craft-async-queue/issues/21 as well but both sounded slightly related.

**Comment by RandomJo** [comment]
I'm not very confident this is a real issue, so I'm going to close it down to avoid any confusion.
