### ISSUE TITLE
Hitting unusual memory limit

### ISSUE THREAD

**Issue by icreatestuff** [ostark/craft-async-queue#23]
The 'Deleting Stale Template Caches' job is failing and complaining about hitting a memory limit

```
The command "/opt/plesk/php/7.2/bin/php craft queue/exec "79272" "300" "1" "" --color=" failed. Exit Code: 255(Unknown error) Working directory: /var/www/vhosts/mydomain.com/httpdocs 

Output: 
================ Error Output: ================ 
PHP Fatal Error 'yii\base\ErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes)' 
```

By my calculations that's a 128M limit, but my php.ini file reads 512MB for `memory_limit`. I've since tried adding the Craft config `'phpMaxMemoryLimit' => '512M'` but that doesn't seem to have made any difference.

I should add I've run the tests for Asyc Queue from Utilities and they run fine so I'm sure the right php binary is being located correctly.

Craft: 3.3.3
Craft-Async-Queue: 2.0.0

Any ideas? Thanks

**Comment by icreatestuff** [comment]
In case it's relevant, the server is running:
- CentOS 6.9
- Plesk 17.8.11
- PHP 7.2.23 in FastCGI mode

I tested turning off the Async Queue plugin and re-tried the jobs which then successfully ran.

If there are any more details I can provide let me know.
Thanks

**Comment by ostark** [comment]
I will take care after my vacation. Thanks.

**Comment by icreatestuff** [comment]
That would be amazing. Do you have any estimation for when this might get look at? Many thanks.

**Comment by ostark** [comment]
@icreatestuff 
Sorry for the late reply. I assume your php-cli environment has a 128M memory limit. Please double check
```
/opt/plesk/php/7.2/bin/php -i | grep memory_limit
```

**Comment by icreatestuff** [comment]
Yeah that is what it’s reporting, which is how the php.ini is set. Though I am confused as the domain’s PHP settings in Plesk are custom, in that it is set to have a higher memory_limit, max_execution_time, post_max_size etc which Craft is working with and reports under utilities/php-info.

Thanks, Matt

**Comment by ostark** [comment]
Solved?

**Comment by icreatestuff** [comment]
Yeah solved if I update the main php.ini file, but not solved if there are domain specific overrides in place. Does the php-cli not take domain level config into account? Can it?

**Comment by ostark** [comment]
hmm, "domain level"? not sure what it means in Plesk.
The command line is usually not aware of a "domain".  < Async Queue runs on the command line.
