### ISSUE TITLE
IIS Environment

### ISSUE THREAD

**Issue by brianjhanson** [ostark/craft-async-queue#24]
We have a client attempting to run this in an IIS environment. Does this plugin support those environments?

**Comment by ostark** [comment]
@brianjhanson 
I guess it does not work out of the box, but you can adjust the command execution using this event:
https://github.com/ostark/craft-async-queue#events

something like `START /B path\to\php.exe {$event->commandLine}`

**Comment by brianjhanson** [comment]
Thanks for the response @ostark! I suspected as much but just wanted confirmation. Thanks for the great plugin either way!
