### ISSUE TITLE
Warning on install

### ISSUE THREAD

**Issue by skramstad** [ostark/craft-async-queue#26]
Got this message from composer on install.
`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`

Anything I can do or are you working on a fix?

**Comment by ostark** [comment]
Can you show the output of

```
composer why container-interop/container-interop
```

**Comment by skramstad** [comment]
@ostark `mrclay/props-dic  2.2.0  requires  container-interop/container-interop (^1.1)`

**Comment by ostark** [comment]
And now

composer why mrclay/props-dic

**Comment by ostark** [comment]
So far, I'd say it is not a dependency of this plugin.

I'd run 

composer update

**Comment by skramstad** [comment]
@ostark thanks for clearing that up. Have a nice day!
