### ISSUE TITLE
The configuration env var should be PHP_PATH instead of PATH_PHP_BINARY

### ISSUE THREAD

**Issue by Stenvdb** [ostark/craft-async-queue#3]
I think there is a typo in the documentation. I couldn't get this working. After some digging I found out there is no such env var named `PATH_PHP_BINARY` in the PhpExecutableFinder class: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/PhpExecutableFinder.php

Renamed it to `PHP_PATH` as it is stated there and everything worked fine.

**Comment by ostark** [comment]
Ah, yes - it changed here
https://github.com/ostark/craft-async-queue/commit/49d01264559c6740f92b3db1c4e70802b4ab236d

I'll update the docs accordingly.
Thanks @Stenvdb

**Comment by khalwat** [comment]
Looks like the `README.md` isn't updated with this info yet.

Fantastic plugin, btw. I'm going to use it on every Craft CMS 3 site.

**Comment by ostark** [comment]
@khalwat thanks for the reminder ;-)

**Comment by ostark** [comment]
@khalwat I'm glad you find it useful! 
@Stenvdb fixed readme
