### ISSUE TITLE
Question: Setting PHP binary location

### ISSUE THREAD

**Issue by ijy** [ostark/craft-async-queue#34]
I'm running an older version of Craft and PHP 7.1 and using this craft-async-queue 1.3.3.

I see in the docs that you mention that by setting the `PHP_BINARY` var in your `.env` you can update your PHP binary location. I have done this but I still see an error related to this plugin:

> Unable to find php binary.

Is there anything else I need to do to tell Async Queue where to look for the binary after adding the var to `.env`?

**Comment by ostark** [comment]
Usually it's not needed to set the path in server with PHP configured properly. 

Is the path in your ENV var correct?

**Comment by ijy** [comment]
In this case I'm using a provisioner (Runcloud) where I'm setting the version of PHP for the 'app' to be different than the default on the server. I've reached out to their support who have confirmed the PHP Binary path and I've set this as a variable in .env. 

There are no other issues with the setup that I can tell but just that I can't get Async Queue 1.3.3 working to run FeedMe imports.

**Comment by bleepsandblops** [comment]
Having the same issue. Have set the PHP_BINARY to /usr/local/bin/php and getting the "Unable to find php binary" message.

**Comment by bleepsandblops** [comment]
FYI @ijy this might be the issue:
`2020-10-12 12:16:07 [-][1][-][error][yii\base\ErrorException:2] yii\base\ErrorException: is_executable(): open_basedir restriction in effect. File(/usr/local/bin/php) is not within the allowed path(s): (/data/sites/web/XXXX:/usr/local/php-7.4/lib/p
hp:/usr/bin:/tmp:/data/vendor-scripts:/data/sites/web/disabled:/etc/ssl/certs) in /data/sites/web/XXXX/vendor/symfony/process/PhpExecutableFinder.php:39`
