### ISSUE TITLE
300 seconds timeout

### ISSUE THREAD

**Issue by jskrivanek** [ostark/craft-async-queue#40]
I get an error after 300 seconds (even though CLI timeout should be 0 and FPM timeout is set to 3600):

```2021-03-10 13:57:51 [-][-][-][error][Symfony\Component\Process\Exception\ProcessTimedOutException] Symfony\Component\Process\Exception\ProcessTimedOutException: The process "'/usr/local/bin/php' 'craft' 'queue/exec' '241276' '300' '1' '0' '--color='" exceeded the timeout of 300 seconds. in /app/vendor/symfony/process/Process.php:1213```

**Comment by jskrivanek** [comment]
Solved it by adding

```
return [
    'components' => [
        'queue' => [
            'ttr' => 3600,
        ],
    ],
];
```

to `config/app.php`.

**Comment by ostark** [comment]
Not directly related to the plugin, but glad you managed to fix it on your own @jskrivanek 🤘🏼

**Comment by brettburwell** [comment]
Thanks @jskrivanek. I bumped into this exact same issue and this tip was super helpful.
