### ISSUE TITLE
On install all image transforms happen again and stall.

### ISSUE THREAD

**Issue by LeoSonnekus** [ostark/craft-async-queue#42]
I just installed this plugin because I have a lot of images on my site so sometimes transforms cause timeouts, and when I login to my admin panel I get a really large number of transforms ending up in my queue, but the queue is not moving at all? This is on MAMP PHP 7.4.9

EDIT: duplicate of: [https://github.com/craftcms/cms/issues/1952](https://github.com/craftcms/cms/issues/1952)

**Comment by ostark** [comment]
@LeoSonnekus You may need to specify the path to the PHP binary
https://github.com/ostark/craft-async-queue#configuration-optional
