### ISSUE TITLE
Should runQueueAutomatically be set to true or false?

### ISSUE THREAD

**Issue by adrienne** [ostark/craft-async-queue#43]
I'm a little unclear on how I should have this configured, @ostark -- can you advise?

**Comment by espensgr** [comment]
Wondering the same thing, so would be nice to just add this to the documentation, so there is no confusion.

**Comment by howells** [comment]
@adrienne @espensgr did you guys work this out?

**Comment by ostark** [comment]
Late ping back: @howells @espensgr @adrienne 

---

A:
There is no need to touch this setting. The plugin overwrites it (to `false`) 
https://github.com/ostark/craft-async-queue/blob/master/src/Plugin.php#L42-L43
