### ISSUE TITLE
Cant install via Craft INterface

### ISSUE THREAD

**Issue by joomkit** [ostark/craft-async-queue#45]
PHP version | 7.4.20
Darwin 20.6.0
MySQL 5.7.34
Craft Pro 3.7.13

When I install via Plugin store I get:

Response: <pre>PHP Fatal Error 'yii\base\ErrorException' with message 'Class GuzzleHttp\Psr7\Response contains 6 abstract methods and must therefore be declared abstract or implement the remaining methods (Psr\Http\Message\RequestInterface::getRequestTarget, Psr\Http\Message\RequestInterface::withRequestTarget, Psr\Http\Message\RequestInterface::getMethod, ...)'

**Comment by ostark** [comment]
Try

composer require ostark/craft-async-queue -W

**Comment by joomkit** [comment]
Thanks! that's done it

**Comment by ostark** [comment]
Or remove
/vendor
composer.json
