### ISSUE TITLE
Async Queue breaks Entry auto-save in Craft 3.7.21 

### ISSUE THREAD

**Issue by MattWilcox** [ostark/craft-async-queue#48]
Tracked this (very weird) issue down to something with this plugin and some sort of change related to Symphony "Process"?

Since running a `composer update` going from Craft 3.7.19.1 to Craft 3.7.21, when editing any Entry there is now an error (screenshot attached) - until AsyncQueue is disabled; when things begin to work properly again.

Attached is a `web.log` of the output of this error when it happens. Andrew Welch managed to track it down as failing on this bit of code in the `/cms/vendor/symphony/process/Process.php` file

```
        $envPairs = [];
        foreach ($env as $k => $v) {
            if (false !== $v) {
                $envPairs[] = $k.'='.$v;
            }
        }
```

<img width="353" alt="Screenshot 2021-11-23 at 14 59 15" src="https://user-images.githubusercontent.com/814039/143074037-cfc4bc51-efe5-4c5a-811b-a4397bfe733a.png">

[web.log.txt](https://github.com/ostark/craft-async-queue/files/7589974/web.log.txt)

**Comment by stevecomrie** [comment]
I'm experiencing the same issue. 

I have two sites on Craft 3.7.21, both with Async Queue, one is working and one is failing.

![Screenshot from 2021-11-23 12-32-51](https://user-images.githubusercontent.com/684903/143078707-ef952790-051b-4c94-8b43-88f57f74b860.png)

The site that's working has symfony/process 5.3.7 installed, the one that's failing is using 5.3.11

Looks like about 19 hours ago, a change was made to symfony/process right at the spot where my error is occuring.

https://github.com/symfony/process/commit/c2098705326addae6e6742151dfade47ac71da1b#diff-a82f1f0b74256d93193ad7436778b39972f484e9286f70f203ef5b2aab052bc7

**Comment by MattWilcox** [comment]
I can confirm that I have a project on Craft 3.7.21 which works and the `composer.lock` for that one is using symphony/process 5.3.7

```
"name": "symfony/process",
            "version": "v5.3.7",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/process.git",
                "reference": "38f26c7d6ed535217ea393e05634cb0b244a1967"
            },
```

and the one that is broken with Craft 3.7.21 is locked at symphony/process 5.3.11
```
"name": "symfony/process",
            "version": "v5.3.11",
            "source": {
                "type": "git",
                "url": "https://github.com/symfony/process.git",
                "reference": "6c99204de85d04ca17f16c466fc61896960b0636"
            },
```

**Comment by MattWilcox** [comment]
This looks like a Symphony bug which they are addressing; just something in AsyncQueue that was exposing (but not causing) the issue.

https://github.com/symfony/symfony/issues/44197

**Comment by ostark** [comment]
Thanks for debugging this!

**Comment by ostark** [comment]
`Symfony/Process` 4.4.35 and 5.3.12 should work
https://github.com/symfony/symfony/pull/44208

Check: `composer info Symfony/Process | grep version`
Update: `composer u Symfony/Process`

**Comment by ostark** [comment]
I'll keep the ticket open for a few days even if I consider this solved.

**Comment by MattWilcox** [comment]
Also confirming that a forced update to Symphony resolves this issue for me too. Nice work all!
