### ISSUE TITLE
Could not acquire mutex lock for the queue (queue)

### ISSUE THREAD

**Issue by tekstrand** [ostark/craft-async-queue#51]
We've been seeing issues, especially when running FeedMe feeds, related to Mutex. For a while we thought it was related to https://github.com/craftcms/cms/issues/10189 but have since stood up Redis and enabled it as the mutex driver for our app. We continued to see issues, and finally thought of disabling async queue. Now that we've done so, the errors are gone and tasks complete successfully.

Please let us know if there's anything additional we can provide to help!

`Uncaught exception 'yii\base\Exception' with message 'Could not acquire a mutex lock for the queue (queue).' in /opt/app/vendor/craftcms/cms/src/queue/Queue.php:780`

**Comment by ostark** [comment]
@tekstrand 
do you experience the issue with this ENV var set?

```
ASYNC_QUEUE_CONCURRENCY=1
```
