### ISSUE TITLE
[BUG] Infinite image transforms

### ISSUE THREAD

**Issue by iamkeir** [ostark/craft-async-queue#57]
When we enable this plugin, our queue starts filling up with an infinitely growing list of image transforms. In each job:

```
Generating pending image transforms</h2>

ID: 352
Status: Pending
Progress: 0%
Time to reserve: 300 seconds
Priority: 2048
Pushed at: Jul 13, 2022, 7:30:42 AM

Job data:
{
    "description": null
}
```

The list just keeps growing and they never process/change from pending. Any thoughts?

**Comment by ostark** [comment]
If the test jobs remain you may need to specify the path to the php executable
https://github.com/ostark/craft-async-queue#configuration-optional

**Comment by iamkeir** [comment]
@ostark that did it, thank you - I should have mentioned I am using MAMP Pro locally, so my PHP path is irregular, and I probably should have RTFM. Thanks for prompt responses, appreciated.

**Comment by ostark** [comment]
NP
