### ISSUE TITLE
Jobs not running after upgrade to Craft 4

### ISSUE THREAD

**Issue by RandomJo** [ostark/craft-async-queue#59]
AsyncQueue has stopped working on several sites after upgrading to Craft 4. When I run the AsyncQueue test, 10 jobs get added to the queue but none of them run after running `./craft queue/run` in my terminal. When AsyncQueue is not installed, quick jobs do run after running the CLI command, including the AsyncQueue tests (after uninstalling and leaving the jobs there to be processed).

I do see this error when I run `./craft queue/run` regardless of whether or not AsyncQueue is installed:

> [ERROR] Queue must be an application component.
> yii\base\InvalidConfigException

It's possible it's related, but I'm having a hard time tracking down the source of that error message.

**Comment by ostark** [comment]
Sorry, I wasn't able to reproduce it with Craft 4.1 
(I'll try it with the latest after fixing my broken setup - yes, something like this happens to me too :-))

**Comment by ostark** [comment]
Not able to reproduce it with Craft 4.2 either. I assume it is somehow related to your unique config/setup.

> I do see this error when I run ./craft queue/run regardless of whether or not AsyncQueue is installed:
> **[ERROR] Queue must be an application component.**
> **yii\base\InvalidConfigException**

Async Queue runs `./craft queue/run` under the hood. If this is broken, it will not work.

~10 lines of the stack trace might me useful to fully understand the issue.

**Comment by ostark** [comment]
Maybe it is related to old Jobs in the queue (created by Craft 3)

https://craftcms.com/docs/4.x/upgrade.html#performing-the-upgrade
> Make sure you don’t have any pending or active jobs in your queue.

**Comment by RandomJo** [comment]
We are going to do some more exploring on our end to see if we can isolate which part of our project config makes the difference. We'll report back later. Heads up that it may be another developer on my team who jumps back in.

**Comment by RandomJo** [comment]
Yes! We are using it for that project. We'll give this a try and let you know.

**Comment by corneliusio** [comment]
@ostark Hopping in here for @RandomJo to confirm that the update to the Relax plugin did in fact fix our issue. Thanks for your help on this!

**Comment by DavidKabelitz** [comment]
@ostark we have the same issue here. Do we need 'runQueueAutomatically' set on true in Craft4?

**Comment by ostark** [comment]
@DavidKabelitz
Does it happen in all environments?
Does ./craft queue/run -v work for you?

**Comment by DavidKabelitz** [comment]
Nope, looks like we need to check some changes related to Craft4. So it's our fault. Thanks for the quick reply.
