### ISSUE TITLE
Latest fixes for Craft 3 / PHP 7.4?

### ISSUE THREAD

**Issue by KarlBishop** [ostark/craft-async-queue#62]
I wanted to install the [latest patch](https://github.com/ostark/craft-async-queue/releases/tag/3.1.0) for `Fixed RateLimiter` etc but this version requires Craft 4 / PHP 8 and we're currently running Craft 3 / PHP 7.4.

We will update at some point of course, but in the meantime, is there any likelihood of these fixes being applied on a separate release for Craft 3 / PHP >= 7.1?

**Comment by frank-laemmer** [comment]
Thanks for the ticket. 

As a fortrabbit client you can easily update to PHP 8 with our Dashboard. Official support for PHP 7.4 will end in November 2022. Many hosting provider will continue to support for some time, including fortrabbit.

I think all Craft 3 versions are compatible with PHP 8. 

The Plugin Store page of this plugin shows that it should be compatible with Craft CMS 3 as well. Maybe you can provide more details, such as the `composer.json` and the exact error you are seeing.

Mind: The AsyncQueue plugin here is not part of the fortrabbit offering.

**Comment by KarlBishop** [comment]
When I try to install on Craft 3 I get this message:

```
Problem 1
    - Root composer.json requires ostark/craft-async-queue 3.1.0 -> satisfiable by ostark/craft-async-queue[3.1.0].
    - ostark/craft-async-queue 3.1.0 requires craftcms/cms ^4.0.0 -> found craftcms/cms[4.0.0, ..., 4.2.5.1] but it conflicts with your root composer.json require (3.7.55.2).
```

My composer.json is:

```
{
    "require": {
        "chasegiunta/scss": "1.0.0",
        "craftcms/cms": "3.7.55.2",
        "craftcms/redactor": "2.10.10",
        "fortrabbit/craft-auto-migrate": "^2.3",
        "fortrabbit/craft-copy": "1.2.4",
        "luwes/craft-codemirror": "2.0.0",
        "mmikkel/reasons": "2.3.1",
        "mmikkel/retcon": "2.5.0",
        "monachilada/craft-matrixtoolbar": "1.0.6",
        "oscarbarrett/craft-asset-lockdown": "1.0.0",
        "ostark/craft-async-queue": "3.1.0",
        "ostark/craft-relax": "1.0.1",
        "putyourlightson/craft-dashboard-begone": "1.0.1",
        "vaersaagod/matrixmate": "1.5.0",
        "vlucas/phpdotenv": "^3.4.0"
    },
    "require-dev": {
        "yiisoft/yii2-shell": "^2.0.3"
    },
    "autoload": {
        "psr-4": {
            "modules\\": "modules/"
        }
    },
    "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "allow-plugins": {
            "yiisoft/yii2-composer": true,
            "craftcms/plugin-installer": true,
            "fortrabbit/craft-auto-migrate": true,
            "treeware/plant": true
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ]
    }
}
```

**Comment by ostark** [comment]
Hi @KarlBishop,

please try: https://github.com/ostark/craft-async-queue/pull/63
