### ISSUE TITLE
Emails fail to send with plugin enabled

### ISSUE THREAD

**Issue by amphibian** [ostark/craft-async-queue#66]
Running into an issue in my production environment with Async Queue. When enabled, emails fail to send wit this error:

> The command "'/opt/cpanel/ea-php81/root/usr/bin/php' '/home/XXXXXX/craftcms/craft' 'queue/exec' '33661' '300' '1' '10845' '--verbose=1' '--color='" failed. Exit Code: 1(General error) Working directory: /home/XXXXX/public_html
> Output: ================
> 2023-01-10 09:16:50 [33661] Sending email notification “Admin Notification” for form “XXXXXXX”. (attempt: 1, pid: 10845)
> - Started Error
> - Output: ================
> - Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 163840 bytes)

Any insight? Disabling the plugin and retrying the queue the emails send instantly.

Running the Async Queue test under Utilities also yields no errors. So maybe this is specifically email related?

- Craft 4.3.6
- PHP 8.1.12
- Email being sent using the Postmark plugin

**Comment by Djive** [comment]
this thing still happening.. 

**Time to reserve** is Hit when plugin enabled.. 
When i disable it. queue works OK:.
