### ISSUE TITLE
Async Queue Test Does not run

### ISSUE THREAD

**Issue by AbbeyDesign** [ostark/craft-async-queue#67]
On my local drive I updated to craft 4.4.5.

The Queue test does not run. The 10 test jobs just sit as pending.

I am using mamp and everything seems set correctly.

**Comment by ostark** [comment]
Does it work in a different environment?

**Comment by okay-type** [comment]
Currently having the same problem, AsyncQueue test jobs and other queue tasks (update search indexes, sending emails from commerce, etc) just sit as Pending. I double checked the PHP location and it appears to be correct. 

Live: 
Craft 3.9.5
PHP 8.0.23 (memory_limit 512M, max_execution_time 120)
AsyncQueue 2.3.0

They are working on my local environment.

Local: 
Craft 3.9.5
PHP 8.0.19 (memory_limit 512M, max_execution_time 120)
AsyncQueue 2.3.0

**Comment by okay-type** [comment]
Just dealt with this again (https://github.com/ostark/craft-async-queue/issues/36) 
Your php location is probably wrong (and don't trust "which php", better off just asking your host).
