### ISSUE TITLE
runQueueAutomatically config setting after installing this plugin?

### ISSUE THREAD

**Issue by harryfk** [ostark/craft-async-queue#71]
This is more of a question than an issue … the readme talks about the Craft config setting `runQueueAutomatically` at the start, but then doesn’t specify what (or if) this should be set to after installing this plugin. Does it matter? Should it be set to `false`? Thanks for the clarification! 🙏

**Comment by erinbit** [comment]
Yes it should be set to false. Otherwise the queue will be processed by the frontend requests as well as the background worker causing all kinds of issues.

**Comment by ostark** [comment]
It does not matter. The plugin overwrites this setting at runtime. @harryfk
