### ISSUE TITLE
Generating articles sitemap Failed

### ISSUE THREAD

**Issue by lucosius** [ostark/craft-async-queue#74]
Hello there,

I started to use this plugin but I cannot get articles sitemap generated. I run AsyncQueue tests and everything is fine but sitemaps get failed.

`The command "'/opt/cpanel/ea-php81/root/usr/bin/php' '/home/telefonai/public_html/craft' 'queue/exec' '26080' '3600' '1' '24820' '--verbose=1' '--color='" failed. Exit Code: 1(General error) Working directory: /home/telefonai/public_html/public Output: ================ 2024-03-16 11:36:08 [26080] Generating articles sitemap (attempt: 1, pid: 24820) - Started Query 1/185 - elements: 18413 Processing element 1/18413 - Reaguoti turėtų kiekvienas „TikTok“ vartotojas: netrukus ši programėlė gali būti visiškai uždrausta, sužinokite, kaip tai palies lietuvius Error Output: ================ Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 32768 bytes)`

My command line:

`nice -n 15 /opt/cpanel/ea-php81/root/usr/bin/php /home/telefonai/public_html/craft queue/run -v > /dev/null 2>&1 &`

I cannot resolve this... Any ideas?

**Comment by ostark** [comment]
Hi @lucosius 

The process fails as it tries to use more than 32MB of memory. Usually there is no memory limit or a much higher limit set for PHP on the command line (under the hood the plugin calls PHP on the command line).

I suggest to increase the limit to at least 256MB.
