### ISSUE TITLE
Undefined constant craft\services\Utilities::EVENT_REGISTER_UTILITIES

### ISSUE THREAD

**Issue by nicolasbinet** [ostark/craft-async-queue#77]
This update is not compatible with Craftcms 4.0.

In the backend we get this error `craft\services\Utilities::EVENT_REGISTER_UTILITIES` which is not available in 4.0.

You should mark it as only  `"craftcms/cms": "^5.0",`

Nicolas

**Comment by gjhead** [comment]
Can confirm, I'm getting the same.  How can I roll back?

**Comment by nicolasbinet** [comment]
@gjhead Modify your composer.json file and set dependency like that :
`"ostark/craft-async-queue": "3.1.1",`

Then run, `composer install` on the CLI

This will revert the change.

**Comment by ostark** [comment]
Arghh, true.

**Comment by ostark** [comment]
I released two new versions

`"ostark/craft-async-queue": "3.2.1",` for Craft 4
`"ostark/craft-async-queue": "4.0.0",` for Craft 5
