### ISSUE TITLE
Upgraded to php 8.3 - Jobs no longer run

### ISSUE THREAD

**Issue by kaspar-allenbach** [ostark/craft-async-queue#80]
I've upgraded everything, but now jobs no longer run.

- Craft: `3.9.13`
- AsyncQueue `2.3.0`
- PHP `8.3.7`

A web.log is being written when I hit `Run Test` but jobs are set and never start.
I can't go pack to `php 8.0` because some plugins no longer support this version.

I disable Async-Queue and the native task manager is running fine.

Any Idea what this could be?

**Comment by controlnocontrol** [comment]
This might help:
https://github.com/ostark/craft-async-queue/issues/73#issuecomment-2153612487

**Comment by kaspar-allenbach** [comment]
Thanks. This was it. Console stopped working due to dotenv
